package com.example.common.core.exception

object MyError {
    const val TIMEOUT_ERROR = "Connection time out"
    const val UNKNOWN_ERROR = "Unknown error occurred"
    const val WRONG_CREDENTIALS = "Wrong credentials"
}